# Generated by Django 3.0 on 2022-04-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='message',
            new_name='mensagem',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='subject',
        ),
    ]
